---
- name: "Set configuration values for tower instance: {{ tower_host }}"
  shell: "tower-cli config {{ item }}"
  with_items:
    - "host {{ tower_host }}"
    - "username {{ tower_username }}"
    - "password {{ tower_password }}"
    - "verify_ssl {{ tower_verify_ssl }}"
  when: tower_login
  no_log: true

- debug:
    var: cluster_credential_git_user